package main

import (
	"time"
)

// config is the struct for the bot internal config file
var config struct {
	// CertificatePath holds a string to the path of a full cert chain in pem format
	CertificatePath string `json:"certificatePath"`

	// PrivateKeyPath holds a string to the path of the corresponding private key to the cert in pem format
	PrivateKeyPath string `json:"privateKeyPath"`

	// BotToken holds the bot token generated by discord to authenticate the bot part
	BotToken string `json:"botToken"`

	// DiscordClientID holds the discord client id generated by discord to identify the oauth part
	DiscordClientID string `json:"discordClientId"`

	// DiscordAuthSecret holds the discord authentication secret generated by discord to authenticate against oauth
	DiscordAuthSecret string `json:"discordOAuthSecret"`

	// HostURL holds the domain name (DNS)
	HostURL string `json:"domain"`

	// HTMLPath holds the path to the mainpage to serve
	HTMLPath string `json:"html"`

	// TemplatePath holds the path to the dashboard template to serve
	TemplatePath string `json:"dashboard"`

	// RedisConnectionString holds the redis database connection string to authenticate with
	RedisConnectionString string `json:"redis"`

	// RedirectURL holds the relative url where oauth requests get redirected to.
	// This has to be identical to your settings at the discord bot settings page.
	RedirectURL string `json:"oAuthRedirect"`

	// WebhookIDInfo writes logs to the given webhook if set up
	// WebhookIDInfo is optional
	WebhookIDInfo string `json:"webhookIdInfo"`

	// WebhookTokenInfo is the auth token for the webhook
	// WebhookTokenInfo is optional
	WebhookTokenInfo string `json:"webhookTokenInfo"`

	// WebhookIDWarning writes logs to the given webhook if set up
	// WebhookIDWarning is optional
	WebhookIDWarning string `json:"webhookIdWarning"`

	// WebhookTokenWarning is the auth token for the webhook
	// WebhookTokenWarning is optional
	WebhookTokenWarning string `json:"webhookTokenWarning"`

	// WebhookIDError writes logs to the given webhook if set up
	// WebhookIDError is optional
	WebhookIDError string `json:"webhookIdError"`

	// WebhookTokenError is the auth token for the webhook
	// WebhookTokenError is optional
	WebhookTokenError string `json:"webhookTokenError"`

	Owner string `json:"owner"`
}

// gw2Account holds the data returned by the gw2 api /v2/account endpoint
type gw2Account struct {
	ID      string   `json:"id"`
	Name    string   `json:"name"`
	World   int      `json:"world"`
	Guilds  []string `json:"guilds"`
	Access  []string `json:"access"`
	Created string   `json:"created"`

	FractalLevel int `json:"fractal_level"`
	DailyAP      int `json:"daily_ap"`
	MonthlyAP    int `json:"monthly_ap"`
	WvWRank      int `json:"wvw_rank"`
}

// worldStruct holds the world data returned by the gw2 api /v2/worlds endpoint
type worldStruct struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type linkInfo struct {
	ID     int    `json:"id"`
	Name   string `json:"name"`
	Linked []int  `json:"linked"`
}

type matchOverview struct {
	ID string `json:"id"`

	// nolint: megacheck
	Worlds struct {
		Red   int `json:"red"`
		Blue  int `json:"blue"`
		Green int `json:"green"`
	} `json:"worlds"`

	AllWorlds struct {
		Red   []int `json:"red"`
		Blue  []int `json:"blue"`
		Green []int `json:"green"`
	} `json:"all_worlds"`

	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

// tokenInfo is the struct to the gw2 api endpoint /v2/tokeninfo
type tokenInfo struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Permissions []string `json:"permissions"`
}

type guildRole struct {
	ID   string
	Name string
}

// guildOptions holds all infos about a discord servers bot settings
type guildOptions struct {
	// gw2 server id to verify for with mode server based
	Gw2ServerID int `json:"gw2Server"`
	// gw2 account api key to verify with for mode user based
	Gw2AccountKey string `json:"apiKey"`
	// mode to select
	Mode mode `json:"mode"`
	// rename users to their ingame account names
	RenameUsers bool `json:"renameUsers"`
	// create all roles even when unused in allservers based mode
	CreateRoles bool `json:"createRoles"`
	// allow linked servers to be verified
	AllowLinked bool `json:"allowLinked"`
	// linked servers get verified role instead of linked servers role
	VerifyOnly bool `json:"verifyOnly"`
	// kick all users from linked servers role when linking changes
	DeleteLinked bool `json:"deleteLinked"`
	// the minimum rank required to be verified
	MinimumRank int `json:"minimumRank"`
}

// dashboardTemplate holds all infos about a discord servers bot settings and options
type dashboardTemplate struct {
	DiscordServers []serversTemplate `json:"discordServers"`
	Gw2Servers     []serversTemplate `json:"gw2Servers"`
	Accounts       []accountTemplate `json:"accounts"`
	Mode           mode              `json:"mode"`
	RenameUsers    bool              `json:"renameUsers"`
	CreateRoles    bool              `json:"createRoles"`
	AllowLinked    bool              `json:"allowLinked"`
	VerifyOnly     bool              `json:"verifyOnly"`
	DeleteLinked   bool              `json:"deleteLinked"`
	MinimumRank    int               `json:"minimumRank"`
}

// serversTemplate holds infos about gw2 or discord servers
type serversTemplate struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Active bool   `json:"active"`
	State  string `json:"state"`
}

// accountTemplate holds infos about gw2 account data
type accountTemplate struct {
	Name   string `json:"name"`
	APIKey string `json:"apiKey"`
	Active bool   `json:"active"`
}

// the mode indicates on which mode the discord server is running the bot
type mode int

const (
	_ mode = iota
	allServers
	oneServer
	userBased
)

type authReason int

const (
	_ authReason = iota
	addUser
	syncUser
	deleteKeys
	useDashboard
)

type oauthState struct {
	Reason authReason `json:"reason"`
	Data   string     `json:"data"`
}

type worldWithRank struct {
	ID int
	rank int
}

type gw2AccountData struct {
	Name string
	Worlds []worldWithRank
}

// TODO:
//   - delete linked / saving worlds